### ISSUE TITLE
add testing

### ISSUE THREAD

**Issue by evriyanaindrasaputra** [evriyanaindrasaputra/next-starter#12]
## Description

add some library for testing 

## Tasks
- [x] install RTL & Setup
- [x] install Jest & Setup
- [x] create some example testing
